/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as EmptyRouteImport } from './routes/empty'
import { Route as BottomRouteImport } from './routes/bottom'
import { Route as IndexRouteImport } from './routes/index'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyRoute = EmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const BottomRoute = BottomRouteImport.update({
  id: '/bottom',
  path: '/bottom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bottom': typeof BottomRoute
  '/empty': typeof EmptyRoute
  '/overview': typeof OverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bottom': typeof BottomRoute
  '/empty': typeof EmptyRoute
  '/overview': typeof OverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bottom': typeof BottomRoute
  '/empty': typeof EmptyRoute
  '/overview': typeof OverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bottom' | '/empty' | '/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bottom' | '/empty' | '/overview'
  id: '__root__' | '/' | '/bottom' | '/empty' | '/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BottomRoute: typeof BottomRoute
  EmptyRoute: typeof EmptyRoute
  OverviewRoute: typeof OverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty': {
      id: '/empty'
      path: '/empty'
      fullPath: '/empty'
      preLoaderRoute: typeof EmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottom': {
      id: '/bottom'
      path: '/bottom'
      fullPath: '/bottom'
      preLoaderRoute: typeof BottomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BottomRoute: BottomRoute,
  EmptyRoute: EmptyRoute,
  OverviewRoute: OverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
